"""06_generate_reports.py — Generate markdown reports from stable_snapshot.json.

Produces:
  - reports/Stable_Dashboard.md (full rewrite)
  - reports/Weekly_Plan.md (full rewrite)
  - reports/Decisions_Log.md (append-only)
"""

import json
import re
from datetime import date, datetime
from pathlib import Path
from typing import Any, Dict, List

ROOT = Path(__file__).resolve().parents[1]
REPORTS_DIR = ROOT / "reports"


def load_snapshot() -> Dict[str, Any]:
    """Load the latest stable_snapshot.json."""
    today = date.today().isoformat()
    path = ROOT / "inputs" / today / "stable_snapshot.json"
    if not path.exists():
        # Try yesterday
        from datetime import timedelta
        yesterday = (date.today() - timedelta(days=1)).isoformat()
        path = ROOT / "inputs" / yesterday / "stable_snapshot.json"
    if not path.exists():
        raise FileNotFoundError(
            f"No stable_snapshot.json found for {today} or previous day.\n"
            f"Run: python scripts/05_build_stable_snapshot.py"
        )
    return json.loads(path.read_text(encoding="utf-8"))


def generate_dashboard(snapshot: Dict[str, Any]) -> str:
    """Generate Stable_Dashboard.md."""
    d = snapshot.get("date", date.today().isoformat())
    balance = snapshot.get("balance", "?")
    horses = snapshot.get("horses", [])

    lines = [
        f"# 🏇 Stable Dashboard",
        f"> **Generated:** {d} | **Balance:** ${balance} | **Horses:** {len(horses)}",
        "",
    ]

    # Summary stats
    in_training = sum(1 for h in horses if h.get("roster_mode", "").upper() in ["", "T"])
    with_noms = sum(1 for h in horses if h.get("nominations"))
    lines.append("## Quick Stats")
    lines.append(f"| Metric | Value |")
    lines.append(f"|--------|-------|")
    lines.append(f"| Active Horses | {len(horses)} |")
    lines.append(f"| Balance | ${balance} |")
    lines.append(f"| With Nominations | {with_noms} |")
    lines.append("")

    # Roster table
    lines.append("## Roster")
    lines.append("| Horse | Track | Cond | Stam | Consist | Mode | Noms |")
    lines.append("|-------|-------|------|------|---------|------|------|")

    for h in sorted(horses, key=lambda x: x.get("name", "")):
        name = h.get("name", "?")
        track = h.get("track", h.get("roster_track", "?"))
        cond = h.get("condition", h.get("roster_cond", "?"))
        stam = h.get("stamina", h.get("roster_stam", "?"))
        consist = h.get("consistency", h.get("roster_consist", "?"))
        mode_raw = h.get("roster_mode", "")
        mode = "🟢" if mode_raw and "R" not in mode_raw.upper() else "🔴" if mode_raw else "?"
        noms = len(h.get("nominations", []))
        nom_str = str(noms) if noms else "—"
        lines.append(f"| {name} | {track} | {cond} | {stam} | {consist} | {mode} | {nom_str} |")

    lines.append("")

    # Upcoming races (horses with nominations)
    nominated = [h for h in horses if h.get("nominations")]
    if nominated:
        lines.append("## Upcoming Races")
        lines.append("| Horse | Date | Track | Race |")
        lines.append("|-------|------|-------|------|")
        for h in nominated:
            for n in h["nominations"]:
                lines.append(f"| {h['name']} | {n.get('date', '?')} | {n.get('track', '?')} | {n.get('race', '?')} |")
        lines.append("")

    # Horses needing attention
    def stam_pct(h: Dict) -> int:
        v = h.get("stamina", "100%").replace("%", "")
        return int(v) if v.isdigit() else 100
    low_stam = [h for h in horses if stam_pct(h) < 80]
    if low_stam:
        lines.append("## ⚠️ Low Stamina")
        for h in low_stam:
            lines.append(f"- **{h['name']}**: {h.get('stamina', '?')}")
        lines.append("")

    lines.append(f"---\n*Auto-generated by `06_generate_reports.py` on {d}*\n")
    return "\n".join(lines)


def generate_weekly_plan(snapshot: Dict[str, Any]) -> str:
    """Generate Weekly_Plan.md."""
    d = snapshot.get("date", date.today().isoformat())
    horses = snapshot.get("horses", [])
    balance = snapshot.get("balance", "?")

    lines = [
        f"# 📅 Weekly Plan",
        f"> **Week of:** {d} | **Balance:** ${balance}",
        "",
    ]

    # Nominated horses → race schedule
    nominated = [h for h in horses if h.get("nominations")]
    if nominated:
        lines.append("## Race Schedule")
        lines.append("| Date | Horse | Track | Race | Notes |")
        lines.append("|------|-------|-------|------|-------|")
        for h in nominated:
            for n in h["nominations"]:
                notes = ""
                stam = h.get("stamina", "100%")
                stam_val = stam.replace("%", "")
                if stam_val.isdigit() and int(stam_val) < 85:
                    notes = f"⚠️ Stam {stam}"
                lines.append(f"| {n.get('date', '?')} | {h['name']} | {n.get('track', '?')} | {n.get('race', '?')} | {notes} |")
        lines.append("")

    # Training priorities
    no_noms = [h for h in horses if not h.get("nominations") and not h.get("record", {}).get("starts")]
    if no_noms:
        lines.append("## Training Priorities (Unraced, No Noms)")
        for h in no_noms:
            lines.append(f"- **{h['name']}** — Track: {h.get('track', '?')}, Stam: {h.get('stamina', '?')}")
        lines.append("")

    # Financial outlook
    lines.append("## Financial Outlook")
    lines.append(f"| Item | Value |")
    lines.append(f"|------|-------|")
    lines.append(f"| Current Balance | ${balance} |")
    lines.append(f"| Nominations Active | {len(nominated)} horses |")
    lines.append("")

    # Action items
    lines.append("## Action Items")
    lines.append("- [ ] Review race entries and set jockey instructions")
    lines.append("- [ ] Monitor stamina for nominated horses")
    lines.append("- [ ] Schedule works for unraced horses")
    lines.append("- [ ] Check for new race calendar entries")
    lines.append("")

    lines.append(f"---\n*Auto-generated by `06_generate_reports.py` on {d}*\n")
    return "\n".join(lines)


def append_decisions_log(snapshot: Dict[str, Any]) -> str:
    """Append a new session entry to Decisions_Log.md (never overwrite)."""
    d = snapshot.get("date", date.today().isoformat())
    log_path = REPORTS_DIR / "Decisions_Log.md"

    # Read existing content
    existing = ""
    if log_path.exists():
        existing = log_path.read_text(encoding="utf-8")

    # Don't add duplicate entry for same date
    if f"## Session: {d}" in existing:
        print(f"  Decisions_Log: skipped (entry for {d} already exists)")
        return existing

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    balance = snapshot.get("balance", "?")
    horses = snapshot.get("horses", [])
    nominated = [h for h in horses if h.get("nominations")]

    entry_lines = [
        "",
        f"## Session: {d}",
        f"*Logged at {timestamp}*",
        "",
        f"- **Balance:** ${balance}",
        f"- **Active Horses:** {len(horses)}",
        f"- **Nominated:** {len(nominated)}",
        "",
        "### Pending Approvals",
        "*(none auto-generated — add manually)*",
        "",
        "---",
    ]

    new_entry = "\n".join(entry_lines)

    if not existing.strip():
        header = "# 📋 Decisions Log\n\n> Append-only log of decisions and approvals.\n\n---\n"
        return header + new_entry
    else:
        return existing.rstrip() + "\n" + new_entry


def main() -> None:
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    snapshot = load_snapshot()
    d = snapshot.get("date", "?")

    # Dashboard (full rewrite)
    dashboard = generate_dashboard(snapshot)
    (REPORTS_DIR / "Stable_Dashboard.md").write_text(dashboard, encoding="utf-8")
    print(f"  Stable_Dashboard.md — {len(dashboard)} chars")

    # Weekly Plan (full rewrite)
    plan = generate_weekly_plan(snapshot)
    (REPORTS_DIR / "Weekly_Plan.md").write_text(plan, encoding="utf-8")
    print(f"  Weekly_Plan.md — {len(plan)} chars")

    # Decisions Log (append-only)
    log = append_decisions_log(snapshot)
    (REPORTS_DIR / "Decisions_Log.md").write_text(log, encoding="utf-8")
    print(f"  Decisions_Log.md — {len(log)} chars")

    print(f"\nReports generated for {d}")


if __name__ == "__main__":
    main()
